# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Github action

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'
    - run: npm ci
    - name: 'Create env file'
      run: |
          touch .env
          echo SUPER_SECRET_KEY="101010" >> .env
          cat .env
    - name: 'Restarting the appp'
      run: |    
          pm2 restart "test node app"